# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Timer
version:      0.04
version_from: Timer.pm
installdirs:  site
requires:
    Template:                      0
    Test::More:                    0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
