---
abstract: 'Display where templates start and stop'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Template::Test: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110540'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-ShowStartStop
no_index:
  file:
    - perlcritic.rc
requires:
  SUPER: 0
  Template::Context: 0
  parent: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/xenoterracide/Template-ShowStartStop/issues
  repository: git://github.com/xenoterracide/Template-ShowStartStop.git
version: 1.0.1
